### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by kanatohodets** [Muon/s3o-tools#1]
Hiya Muon, this is Nemo from the Spring forums -- blast from the past :)

Spring:1944 would really like to build some things based on s3o-tools for mass-renaming s3o pieces, but the licensing status for s3o-tools as a whole isn't clear. I saw the "Python File Format Interface" license for the vertex cache file (3 clause BSD), but wasn't sure if that was meant for everything. Would you mind adding a LICENSE file to this repo to cover everything inside? We'd be very appreciative if it were one that allowed derivative works.

Thanks! Hope you're still making awesome things.

**Comment by Muon** [comment]
It is done! Note that `vertex_cache.py` is not my code, hence the other license.
